// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import java.util.concurrent.TimeUnit;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class ConversorEscalasServletTest {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @BeforeEach
    public void setUp() {
        setupGeckoDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<>();
    }

    void setupGeckoDriver() {
        WebDriverManager.firefoxdriver().setup();
        driver = new FirefoxDriver();
        options();
    }

    private void options() {
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void shouldBeConvert100CelsiusTo212Fahrenheit() {
        driver.get("http://localhost:8080/servlet-conversor-celsius-fahrenheit/");
        driver.findElement(By.id("temperatura")).click();
        driver.findElement(By.id("temperatura")).sendKeys("100");
        driver.findElement(By.id("fahrenheit")).click();
        driver.findElement(By.id("btnSubmit")).click();
        assertEquals(
            "Ao converter de Celsius para Fahrenheit o valor de 100,00, o resultado é 212,00",
            driver.findElement(By.cssSelector("h1")).getText()
        );
    }
    
    @Test
    public void shouldBeConvert212FahrenheitTo100Celsius() {
        driver.get("http://localhost:8080/servlet-conversor-celsius-fahrenheit/");
        driver.findElement(By.id("temperatura")).click();
        driver.findElement(By.id("temperatura")).sendKeys("212");
        driver.findElement(By.id("celsius")).click();
        driver.findElement(By.id("btnSubmit")).click();
        assertEquals(
            "Ao converter de Fahrenheit para Celsius o valor de 212,00, o resultado é 100,00",
            driver.findElement(By.cssSelector("h1")).getText()
        );
    }
    
    @Test
    public void shouldBeConvertMinus12Point2CelsiusTo10Point4Fahrenheit() {
        driver.get("http://localhost:8080/servlet-conversor-celsius-fahrenheit/");
        driver.findElement(By.id("temperatura")).click();
        driver.findElement(By.id("temperatura")).sendKeys("-12.2");
        driver.findElement(By.id("fahrenheit")).click();
        driver.findElement(By.id("btnSubmit")).click();
        assertEquals(
            "Ao converter de Celsius para Fahrenheit o valor de -12,20, o resultado é 10,04",
            driver.findElement(By.cssSelector("h1")).getText()
        );
    }
    
    @Test
    public void shouldBeConvert60FahrenheitTo15Point56Celsius() {
        driver.get("http://localhost:8080/servlet-conversor-celsius-fahrenheit/");
        driver.findElement(By.id("temperatura")).click();
        driver.findElement(By.id("temperatura")).sendKeys("60");
        driver.findElement(By.id("celsius")).click();
        driver.findElement(By.id("btnSubmit")).click();
        assertEquals(
            "Ao converter de Fahrenheit para Celsius o valor de 60,00, o resultado é 15,56",
            driver.findElement(By.cssSelector("h1")).getText()
        );
    }
    
    // TODO: remover
    @Test
    public void falhaPropositalmente() {
        fail();
    }
}
